### ISSUE TITLE
Use AdminClient for topic creation

### ISSUE THREAD

**Issue by viktorsomogyi** [linkedin/cruise-control#1096]
If the given API is available in the broker we should prefer using `AdminClient` instead of Zookeeper.

**Comment by viktorsomogyi** [comment]
@efeg please feel free to assign it to me, happy to resolve it if you think it'd be a useful addition.

**Comment by viktorsomogyi** [comment]
The functionality is available since Kafka 2.2 but if we want to be compatible with Kafka 2.0 even, then I think we could try a try-and-fallback mode where first it tries to use the AdminClient and if unsuccessful, falls back to Zookeeper.

**Comment by efeg** [comment]
Hi @viktorsomogyi 
I agree that `AdminClient` should be preferred instead of `AdminZkClient` and your proposed solution with fallback to `Zookeeper` seems reasonable to me. I believe currently topic creation uses Zookeeper in `KafkaSampleStore` and `LoadMonitorTaskRunnerTest`. Please feel free to create a PR with the proposed changes.

**Comment by efeg** [comment]
Closing the issue as the current version depends on AdminClient for topic creation.
