### ISSUE TITLE
How does the window size and the number of windows affect proposals?

### ISSUE THREAD

**Issue by matthinograb** [linkedin/cruise-control#1149]
Our team recently enabled self-healing in a test environment, and I noticed that self-healing happen once an hour, nearly every hour. We found that this was because the broker & partition window sizes were 1 hour (default configuration).

This made me wonder, what happens when we change:
1. window size
2. number of windows

I was hoping you could help me establish a better mental model around these configurations. 

Below are a few hypotheses that I have, but would appreciate additional insight from the community or maintainers 😸

---

### 1. Effect of changing window size
I assume that even though the goal violation detector will run once every `goal.violation.detection.interval.ms` minutes, it will not detect violations until the window is closed. Thus, larger window sizes will result in a slower time to detect distribution imbalances and violations like rack-awareness. So, smaller window sizes would be preferred in most cases.

Smaller window sizes would result in more frequent self-healing actions, but this could potentially be mitigated using low utilization thresholds.

Are there any other downsides to using small window sizes? Sensitivity to outliers when aggregating - or is this mitigated because we're collecting aggregated samples from Yammer, etc.?

### 2. Effect of changing number of windows
I would assume that the number of windows does not play a large role in proposal generation itself. Rather, the amount of overall data taken into consideration (`window_size` * `num_windows`) affects the proposal.

Additionally, increasing the number of monitored windows would increase the memory requirements for the MetricSampleAggregator's buffer, and may affect the computational requirements to create proposals.

### 3. Overall input data size
I assume that the more time that is monitored (`window_size` * `num_windows`), the longer it will take for Cruise Control to bootstrap on a new cluster. Beyond this, I'm still not really sure how increasing/decreasing the time affects proposals, etc.

Relevant configurations:
- `broker.metrics.window.ms` and `partition.metrics.window.ms`
- `num.broker.metrics.windows` and `num.partition.metrics.windows`

**Comment by efeg** [comment]
@matthinograb Thanks for the detailed writeup and sorry for my delayed response!

> We found that this was because the broker & partition window sizes were 1 hour (default configuration).

While partition window size is relevant, broker window size does not matter for goal-violation detection. The cluster model that goal violation detector uses is populated based on the aggregated partition windows.

#### Effect of changing window size

Goal violation detector will use the cluster model at the time of goal violation check. If a new partition window is not yet rolled out at the time of the check (i.e. `goal.violation.detection.interval.ms` < `partition.metrics.window.ms`), then  the load on partitions will be slightly stale. However, for goals that do not require checking the load (e.g. Rack Awareness, Replica Distribution), the detector will identify any violations based on the real time distribution. So that is not a reason to prefer small window sizes.

> Smaller window sizes would result in more frequent self-healing actions, but this could potentially be mitigated using low utilization thresholds.

Smaller window sizes may result in more frequent self-healing actions if (1) the cluster load fluctuates a lot and (2) the number of windows is small. The strictness of each goal can be adjusted/relaxed individually to trigger fewer goal violations.
Small windows would also let collecting fresh data faster after a long execution, during which partition load sampling is paused.

> Are there any other downsides to using small window sizes? Sensitivity to outliers when aggregating - or is this mitigated because we're collecting aggregated samples from Yammer, etc.?

If small windows are used, to cover the same partition load history, one needs to use more windows. For example, suppose we want CC to make self-healing decision based on load history of the pas hour. To do so, I can either use (1) 12 partition windows each 5-minute or (2) 1 partition window, which is 1-hour long. The first scenario requires CC instance to keep more data in memory; hence, increases the memory pressure of CC instance. However, the latter scenario makes CC self-healing less sensitive to changes and when CC is setup for the first time, it takes ~1 hour for CC to be able to start any execution (e.g. rebalance).

#### Effect of changing number of windows

Other than the points that you brought up, having more windows while keeping the window size the same would let CC make decisions based on a longer history: this is useful if there is a daily or weekly pattern that we would like CC to rebalance the cluster against.

#### Overall input data size

> I assume that the more time that is monitored (window_size * num_windows), the longer it will take for Cruise Control to bootstrap on a new cluster.

This is correct. also, as mentioned in the previous section, this would let CC make decisions based on a longer history.

**Comment by efeg** [comment]
@matthinograb Closing the issue -- please feel free to reopen if you have further questions.

**Comment by stanislavkozlovski** [comment]
@efeg @matthinograb do you have any opinions on how this interacts with rebalances?

e.g isn't a partition/broker window considered "stale" once a rebalance (or a couple) has happened since the window was closed?
