### ISSUE TITLE
Repeated Bootstrap disconnected logs

### ISSUE THREAD

**Issue by devkmsg** [linkedin/cruise-control#1249]
We are running Kafka 2.4.1 and cruise-control-metrics-reporter 2.0.39.  We are seeing the below log statement almost constantly.

`[kafka-producer-network-thread | CruiseControlMetricsReporter] WARN  org.apache.kafka.clients.NetworkClient  - [Producer clientId=CruiseControlMetricsReporter] Bootstrap broker SOMEIP:9092 (id
: -1 rack: null) disconnected`

Should we be using a more recent version of the reporter?  The [Environment Requirements](https://github.com/linkedin/cruise-control#environment-requirements) in the README doesn't cover Kafka 2.4 or 2.5, so I'm unsure what version we should be using.

`The current master branch of Cruise Control is compatible with Apache Kafka 2.0, 2.1, 2.2, and 2.3 (i.e. Releases with 2.0.*)`

**Comment by efeg** [comment]
The warning message `Bootstrap broker XXX (id : -1 rack: null) disconnected` comes from [here](https://github.com/apache/kafka/blob/2.4/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java#L1032).
This message indicates that a connection to the bootstrap broker was established, but was disconnected before metadata could be obtained. This might indicate some network issues or issues with the broker running on `SOMEIP:9092`.

- The recommended CC versions to use with different versions of Kafka have been updated recently (please see [Environment Requirements](https://github.com/linkedin/cruise-control#environment-requirements)) -- would you verify whether you were running a `2.4.*` or a `2.0.*` version of CC -- i.e. CC running along with 2.0.39 metrics-reporters? However, I suspect that this exception is not due to using a CC version inconsistent with the running Kafka version.

**Comment by efeg** [comment]
Closing the issue. @devkmsg please feel free to reopen if you have further questions.
