### ISSUE TITLE
Is replica throttle not available in kafka 1 branch?

### ISSUE THREAD

**Issue by aryaKetan** [linkedin/cruise-control#1330]
Hi,
We are running a kafka 1.0.2 cluster and using cruise control to manage operations. We noticed that PR#748 is merged to kafka 2 branch. Any reason this was not committed to kafka 1? If we cherry-pick this and run, is there any risk we should be aware of?

**Comment by efeg** [comment]
`kafka_0_11_and_1_0` branch does not have support for `byte-rate-based` replication throttling. Since [KIP-73]( https://cwiki.apache.org/confluence/display/KAFKA/KIP-73+Replication+Quotas) is supported on Kafka `0.10.1.0+`, it should be possible to cherry-pick the relevant commits. We stopped adding features to `kafka_0_11_and_1_0` branch, as it corresponds to a fairly outdated Kafka version.
