### ISSUE TITLE
Ignore unfixable partitions during rebalance

### ISSUE THREAD

**Issue by mavemuri** [linkedin/cruise-control#1423]
Hello, 
I have a cluster with 3 brokers and some topics with replication factor=3. I also have some topics with replication factor=2. When I bring down a broker, cruisecontrol gets stuck with one of the topics where the rf=3 and doesn’t try to fix even the fixable rf=2 topics. Is there some way around this? Ideally, cruisecontrol would want to fix what it can fix and leave the rest

**Comment by efeg** [comment]
Hi @mavemuri,

Thanks for the detailed explanation of the scenario.
Unfortunately, CC goals are not designed to generate proposals that would leave the cluster with offline replicas; hence, I suspect that simply dropping a subset of offline replicas from `selfHealingEligibleReplicas` would be insufficient to achieve the desired behavior with the existing goals.

The recommended solution for this case is to 
1. Add 1 more broker to the cluster so that the cluster now has 3 alive brokers and 1 dead broker with offline replicas,
2. Then either run (1) `remove_broker` with the failed broker id or (2) `fix_offline_replicas`.

This will ensure that all replicas reside on the alive brokers.
