### ISSUE TITLE
Insufficient number of racks to distribute each replica

### ISSUE THREAD

**Issue by qz-fordham** [linkedin/cruise-control#1451]
Trying to understand how rack-awareness goal works in Cruise Control.

I have a cluster with 8 nodes and 4 racks (2 nodes each). Sometimes, when I try to rebalance based on all hard goals (including RackAwareGoal) and maybe an optional Disk Usage Distribution goal, I will get 

> Insufficient number of racks to distribute each replica (Current: 4, Needed: 6)
> Insufficient number of racks to distribute each replica (Current: 4, Needed: 7) `Needed` is not always the same.

From the source code, it shows the error msg will happen when `clusterModel.maxReplicationFactor() > numAliveRacks`. I wonder why this is happening. One thing I can ensure is that all my topics have at most 4 replicas. It doesn't make sense to me if 6 or 7 is needed. 

Also, this often happens when there are producers & consumers actively processing messages (message processing & rebalance happening the same time).

Appreciate any pointer or advice. Thank you in advance.

**Comment by efeg** [comment]
Hi @qz-fordham 

> One thing I can ensure is that all my topics have at most 4 replicas. It doesn't make sense to me if 6 or 7 is needed.

Replication factor is a partition level property. The response indicates that there are partitions with 6 and 7 replicas. You can 
1. Retrieve the list of partitions with their replicas using `kafka_cluster_state` endpoint with `verbose=true` parameter to see which partitions have a replication factor 6 or 7 -- inconsistent replication factor across partitions of a topic can happen if you are using Kafka 2.3 or before and controller dies during an ongoing execution
2. you can fix the replication factor of all or selected topics using CC's `topic_configuration` endpoint (see https://github.com/linkedin/cruise-control/wiki/Change-topic-replication-factor-through-Cruise-Control), and
3. you can change your goal configs (i.e. there are multiple related configs) to use `RackAwareDistributionGoal` rather than `RackAwareGoal` -- see their javadoc for details on how they work.
Hope it helps!

**Comment by qz-fordham** [comment]
Hi @efeg   

Thanks for the information. They are indeed really helpful. We actually built `tags/2.5.10` as binary, where `RackAwareDistributionGoal` was not supported. We can definitely update the binary version. In terms of stability and feature richness, which tag would you recommend? We have a Confluent 5.5.x (Apache 2.5.x) Kafka cluster.   

On the other hand, since we are not using Kafka 2.3 or before version, is there any chance the exception is caused by legacy CC internal? Just trying to understand the cause. 

A totally unrelated concern of documentation, do you think it's worth adding the `/review` API in the [REST API](https://github.com/linkedin/cruise-control/wiki/REST-APIs) docs? Maybe give a brief mention with a hyperlink to the existing [2-step-verification](https://github.com/linkedin/cruise-control/wiki/2-step-verification-for-POST-requests) docs?

**Comment by efeg** [comment]
I would recommend the latest published release -- the [release notes](https://github.com/linkedin/cruise-control/releases) provide details on the new features, bug fixes, and improvements for each tag.

> since we are not using Kafka 2.3 or before version, is there any chance the exception is caused by legacy CC internal

There is no known issue that might cause such an inconsistency in Kafka 2.5. Not sure what the root cause could be -- if the `kafka_cluster_state` endpoint with `verbose=true` parameter shows that there are topics, whose all partitions are consistent and higher than RF=4, maybe users have created those topics with that high RF?

> do you think it's worth adding the `/review` API in the [REST API](https://github.com/linkedin/cruise-control/wiki/REST-APIs) docs? Maybe give a brief mention with a hyperlink to the existing [2-step-verification](https://github.com/linkedin/cruise-control/wiki/2-step-verification-for-POST-requests) docs?

Absolutely! Please feel free to create a PR if you'd be interested in contributing on this.

**Comment by qz-fordham** [comment]
@efeg Thanks for the suggestion. I will get the latest release for it.   

> if the kafka_cluster_state endpoint with verbose=true

Forget to mention this before, but I did check with `verbose=true` when there is no rebalance job running, no partition with replication factor > 4 exists. So I think that really only happens when rebalance task is running. Besides, normally I force RackAwareGoal in my rebalance, it shouldn't let the task starts if there is any partition with rf>4. What I experienced was the executor will run for a couple of GB migrations then fail due to that error. Anyway, no worries, I think will update the version and get kafka_cluster_state verbosely next time when a similar thing happens. It will be easier to figure out that way then. Thank again.
> Absolutely! Please feel free to create a PR if you'd be interested in contributing on this.  

I will make a PR for that. Thanks.
