### ISSUE TITLE
partition moves can severely cripple cluster activity and client acks

### ISSUE THREAD

**Issue by brettrann** [linkedin/cruise-control#150]
I know this is already on the radar from reading Gitter but I can't find an issue for it, so creating one. And I know most of you will already be familiar, I'll just write something thorough and clear for those that aren't. If there's work in progress it would be good to know too!

When allowing cruise control to trigger partition reassignments, even setting it to 1 move per broker using config, it can cripple cluster performance, and in our case severely increases the ack time for some acks=all producers, with the 95th percentile jumping to 15s or more.

This was addressed in 0.10.1.0 with throttling options intended to allow partition reassignments to be done with a lighter impact on a running cluster:
https://cwiki.apache.org/confluence/display/KAFKA/KIP-73+Replication+Quotas
https://issues.apache.org/jira/browse/KAFKA-1464

The supplied kafka-reassign-partitions.sh script applies the throttles, and the code it calls is here:
https://github.com/apache/kafka/blob/trunk/core/src/main/scala/kafka/admin/ReassignPartitionsCommand.scala

And cruise control currently calls the ZKUtils directly to update a partition reassigmnent:
https://github.com/linkedin/cruise-control/blob/master/cruise-control/src/main/scala/com/linkedin/kafka/cruisecontrol/executor/ExecutorUtils.scala#L95
```
zkUtils.updatePartitionReassignmentData(newReplicaAssignment)
```
which is this:
https://github.com/apache/kafka/blob/trunk/core/src/main/scala/kafka/utils/ZkUtils.scala#L790

**Comment by brettrann** [comment]
A super duper high level overview of how the throttling configs work:

Internally there are these configs that can be set, with the rate in bytes:
```
kafka-configs.sh --zookeeper zoo1:2181/kafka --entity-type brokers --entity-name $brokerid --alter --add-config follower.replication.throttled.rate=30000000
kafka-configs.sh --zookeeper zoo1:2181/kafka --entity-type brokers --entity-name $brokerid --alter --add-config leader.replication.throttled.rate=30000000
```
By themselves they do nothing. They can be referenced as a topic config to leader and follower with wildcards or a partition:broker comma separated list. (take care the documentation around this can be a bit inconsistent and confusing. I'm basing this on what the code currently does)

```
kafka-configs.sh --zookeeper zoo1:2181/kafka --entity-type topics --entity-name my-test-topic --alter --config 'leader.replication.throttled.replicas=*'
# or fine grained
kafka-configs.sh --zookeeper zoo1:2181/kafka --entity-type topics --entity-name my-test-topic  --alter --config follower.replication.throttled.replicas=99:1,99:2
kafka-configs.sh --zookeeper zoo1:2181/kafka --entity-type topics --entity-name my-test-topic --alter --config leader.replication.throttled.replicas=99:3
```

This is used by operators when using the kafka-reassign-partitions.sh script by specifying the --throttle argument when executing a partition reassignment, and it needs to be run again with --verify after the assignments are finished to ensure all the configs are removed.

Here's how that works:

Lets say I have a topic maxwell and a partition 23, currently assigned to partitions [2,5]. It has min.insync.replicas=2 and somehow it ended up with an RF of 2 instead of 3. Oops!
I Want to add broker 1 as a replica with a partition reassignment, and throttle the expansion to 1000 bytes / sec.
```
{"partitions":[
    {"topic": "maxwell", "partition": 23, "replicas": [2,5,1] }
],"version":1}
```
```
kafka-reassign-partitions.sh --zookeeper zoo1.pod100:2181/kafka --reassignment-json-file reassign.json --execute --throttle 1000
...
Warning: You must run Verify periodically, until the reassignment completes, to ensure the throttle is removed. You can also alter the throttle by rerunning the Execute command passing a new value.
The throttle limit was set to 1000 B/s
Successfully started reassignment of partitions.
```

Lets look at the configs it set:
```
$ for broker in {1..5}; do kafka-configs.sh --zookeeper zoo1:2181/kafka --entity-type brokers --entity-name $broker --describe ; done
Configs for brokers '1' are leader.replication.throttled.rate=1000,follower.replication.throttled.rate=1000
Configs for brokers '2' are leader.replication.throttled.rate=1000,follower.replication.throttled.rate=1000
Configs for brokers '3' are leader.replication.throttled.rate=1000,follower.replication.throttled.rate=1000
Configs for brokers '4' are leader.replication.throttled.rate=1000,follower.replication.throttled.rate=1000
Configs for brokers '5' are leader.replication.throttled.rate=1000,follower.replication.throttled.rate=1000
```

And the topic throttle:
```
kafka-configs.sh --zookeeper zoo1:2181/kafka --entity-type topics --entity-name maxwell --describe
Configs for topic 'maxwell' are leader.replication.throttled.replicas=23:2,23:5,follower.replication.throttled.replicas=23:1,retention.ms=2592000000,max.message.bytes=2000000,min.insync.replicas=2
```

The existing ISR partitions get the leader throttle, and the target broker gets the follower throttle.

```
kafka-reassign-partitions.sh --zookeeper zoo1.pod100:2181/kafka --reassignment-json-file reassign.json --verify
Status of partition reassignment:
Reassignment of partition maxwell-23 is still in progress
```
taking a long time. 1000 bytes was probably too small for a 50GB partition. Let's bump it 50 MB/s.

```
kafka-reassign-partitions.sh --zookeeper zoo1.pod100:2181/kafka  --reassignment-json-file reassign.json --execute --throttle 50000000
There is an existing assignment running.
```
Which actually silently increases the throttle.
```
kafka-configs.sh --zookeeper zoo1:2181/kafka --entity-type brokers --entity-name 1 --describe
Configs for brokers '1' are leader.replication.throttled.rate=50000000,follower.replication.throttled.rate=50000000
```

And when the expansion is finished, it's necessary to run --verify one more time which will clear all the throttling configs.

**Comment by efeg** [comment]
@brettrann, thanks for creating the issue and providing an overview!
Integration with replication quotas, as described in KIP-73, is definitely an important feature and is in our road map.

**Comment by BDeus** [comment]
Hi @efeg do you know if the abiliity to set the throttle rate is still in the road map?

**Comment by efeg** [comment]
@BDeus It indeed still is -- but I would say it is not the top priority item within the next 2 months or so.

**Comment by aaronlevin-stripe** [comment]
@efeg here's a proposal for a throttle design based on my understanding of the codebase. Would love some feedback and we're happy to submit a PR if it works for you. I think the most controversial part will be around removing throttles when the rebalance is complete, otherwise I think it's straight forward.

We'll also be putting forward a proposal around state-management in Cruise Control as the lack of state made the throttle implementation a little harder.

---

# Cruise Control Throttle Design

Authors: @aaronlevin-stripe, @nat-stripe, @joshrosen-stripe

## Motivation

Cruise Control plans boil down to two types of changes: partition leadership movement and partition replica movement. Currently, when Cruise Control executes a replica movement it does not apply any replica quotas per KIP-73. 
 
We’ve learned through experience that applying quotas is an important part of maintaining cluster performance and stability during partition movement. 

While it is possible for us to apply quotas outside of Cruise Control, it’s preferable to operators for Cruise Control to manage applying and removing quotas.

## Goals

- An operator should have the ability to specify a replica quota (a `throttle` ) in units of `bytes/second` when executing a rebalance in Cruise Control.
- The `throttle` should have the same meaning as the `throttle` parameter in `kafka-reassign-partitions.sh`
- An operator should not have to manually remove the `throttle` when Cruise Control completes a rebalance.
- An operator should not have to manually the `throttle` when Cruise Control is restarted during a rebalance.
- If a `throttle` is already present, it will be not be updated.
- If a `throttle` was passed to Cruise Control, when a rebalance is complete that `throttle` is removed (this is the current behaviour of `reassign-partitions.sh` ). This means that if you have pre-existing throttles, then you should not use the `throttle` feature as using it will result in the removal of those throttles when the rebalance is complete. 
    - Because Cruise Control does not track any state it is difficult to know whether a pre-existing throttle was user-specified or an artifact from an interrupted or failed Cruise Control-executed rebalance. 
Non-Goals
- A rebalance `throttle` will be a global throttle for each rebalance (as it is in `kafka-reassign-partitions.sh`). We will not expose per-replica throttle amounts to the operator.

## Design


### 1. Add a `throttle` param to the `rebalance` endpoint


- `throttle` parameter will be in units of `bytes/second`
- `throttle` parameter will be of type `int`


### 2. Thread `throttle` through the application for use in `ExecutorUtils.executeReplicaAssignmentTasks`

This will require threading the `throttle` through several classes in Cruise Control:


- `RebalanceParameters`
- `KafkaCruiseControl.rebalance`
- `KafkaCruiseControl.executeProposals`
- `Executor.executeProposals`
- `Executor.startExecution`
- `ProposalExecutionRunnable`
    - `moveReplicas()`, and
    - `moveLeadership()`
- `ExecutorUtils.executeReplicaAssignmentTasks`


### 3. Update `ExecutorUtils.executeReplicaAssignmentTasks` to apply and then remove throttles.

This will involve copying much of the code from `ReassignPartitionsCommand` that handles setting the throttle config in zookeeper.


- If a `throttle` is provided to `executeReplicaAssignmentTasks` and there is a pre-existing throttle, then the pre-existing throttle will be used and then removed when the rebalance is complete.
- If a `throttle` is provided to `executeReplicaAssignmentTasks` and there is not a pre-existing throttle, then the `throttle` provided will be used and then removed when the rebalance is complete.
- If a `throttle` is not provided to `executeReplicaAssignmentTasks`, then rebalancing will behave as it does now.
 
## Open Questions

- Are we handling the scneario with pre-existing throttles correctly? What happens if there’s an existing throttle present? Should we take ignore or take the `minimum`?
- Is there a way we can reuse the code from `ReassignParititonsCommand` that applies the throttles?
Rejected Alternatives
- Manage throttling ourselves via `dataToMove` and `_finishedDataMovementInMB` with `Executor.moveReplicas()`
    - quota management is better handled in kafka than by us.
    - also not even sure this is possible.

## Risks
- Applying a throttle may be easy, but managing and removing throttles during various failure and startup cases may be very difficult to automate.

**Comment by efeg** [comment]
@aaronlevin-stripe Thanks for the detailed design document!

* (Related to `non-goals` and keeping the `rebalance` throttling self-contained):  Does the design ensure that the `global throttle` is limited to the ongoing replica movements started _only_ by Cruise Control (CC)? In other words, as opposed to the expected `URP`s (i.e. being reassigned by CC), if there are unexpected `URP`s (i.e. fell out of `ISR`) while a reassignment throttle is in place, I assume such partitions will not be affected from the user-enforced `rebalance` quota. This will ensure that the rebalance quota will not have adverse affects on the speed at which the cluster recovers from unexpected `URP`s.

`KIP-73` supports setting replication quotas in replica granularity. Hence, the throttled follower replica list may contain only the replicas that are actively being reassigned by CC. If the partition has multiple followers that are being reassigned, we may also need to adjust the replication quota on the leader-side to properly throttle leader and follower replicas of a partition.

* If the cluster has existing `URP`s when the user requests a `rebalance` (e.g. due to offline replicas), should we apply a different quota to the replicas of such partitions? This would help keeping the recovery time for such under replicated partitions at minimum.

* Do we apply the same `rebalance` quota when the action is triggered by CC due to goal violation self-healing? For simplicity, we may choose to keep this patch limited to the user-initiated `rebalance` requests, and then later expand it to apply to (1) `remove_broker` (2) `fix_offline_replicas` (3) `add_broker`, and (4) self-healing actions initiated by CC, as well.

* `Add a throttle param to the `rebalance` endpoint` -> Should we have separate parameters for leader and follower throttle rate? -- i.e. `leader_throttle` and `follower_throttle`. This will be relevant if there are partitions with `RF > 2`, because in such cases, depending on the specific implementation, either `leader_throttle` will be violated or `follower_throttle` will not be honored. Alternatively, we may discuss enforcing the throttling only to the followers, but not the leaders.

* `Thread throttle through the application for use in ExecutorUtils.executeReplicaAssignmentTasks` -> At a high-level, this looks reasonable to me.

* `If a throttle is provided to executeReplicaAssignmentTasks and there is a pre-existing throttle, then the pre-existing throttle will be used and then removed when the rebalance is complete.` -> I am curious whether it would be possible to reset it back to the `pre-existing` throttle?

* As a side-note, I agree that rejected alternatives are not possible -- i.e. CC cannot perform quota management by itself.

Once again, thanks for the detailed design!

**Comment by aaronlevin-stripe** [comment]
@efeg thanks for the feedback. Overall it sounds like what we've proposed is pretty much inline so we'll start on an implementation and get you a PR soon (we may start this week, if not then definitely start next week). However, let me address your questions:

> Does the design ensure that the global throttle is limited to the ongoing replica movements started only by Cruise Control (CC)? In other words, as opposed to the expected URPs (i.e. being reassigned by CC), if there are unexpected URPs (i.e. fell out of ISR) while a reassignment throttle is in place, I assume such partitions will not be affected from the user-enforced rebalance quota. This will ensure that the rebalance quota will not have adverse affects on the speed at which the cluster recovers from unexpected URPs.

Yes, the throttle should be limited only to ongoing replica movements started by Cruise Control. Basically there is some code in `executeReplicaAssignmentTasks` where we'd apply the throttle before  each move and then remove then throttle when done. So any other unexpected URPs will not be throttled by Cruise Control.

> If the cluster has existing URPs when the user requests a rebalance (e.g. due to offline replicas), should we apply a different quota to the replicas of such partitions? This would help keeping the recovery time for such under replicated partitions at minimum.

My thoughts are that if a quota already exists we should leave it be (however I don't feel strongly). I'm assuming that any pre-existing quota is there because a kafka cluster administrator set it or because a previous Cruise Control-executed rebalance was restarted/killed/failed before completing. In both these cases I feel it's safest not to touch the existing quota.

> Do we apply the same rebalance quota when the action is triggered by CC due to goal violation self-healing? For simplicity, we may choose to keep this patch limited to the user-initiated rebalance requests, and then later expand it to apply to (1) remove_broker (2) fix_offline_replicas (3) add_broker, and (4) self-healing actions initiated by CC, as well.

My thoughts are that for this PR we should focus only on the user-initiated rebalances and that later we can add support for goal violation self-healing. Supporting goal violation self-healing is a little more complicated because the throttles need to be captured as part of the goal themselves.

> Add a throttle param to the rebalance endpoint -> Should we have separate parameters for leader and follower throttle rate? -- i.e. leader_throttle and follower_throttle. This will be relevant if there are partitions with RF > 2, because in such cases, depending on the specific implementation, either leader_throttle will be violated or follower_throttle will not be honored. Alternatively, we may discuss enforcing the throttling only to the followers, but not the leaders.

I suggest we start with prior art and do the same as `rebalance-partitions.sh` (a global throttle that is applied to both leaders and followers) and then we can likely support both cases in a future PR (e.g. allowing a `throttle` param, `leader_throttle` param, _and_ `follower_throttle` param with some logic to determine what the final param (or fail) if different combinations are present).

> I am curious whether it would be possible to reset it back to the pre-existing throttle?

When we complete a rebalance, the question around whether we remove the throttle or reset it back to the pre-existing throttle is a trade-off between the following:
* (reset throttle to pre-existing throttle): preserve user-specified throttles
* (remove throttle when rebalance is done): ensure Cruise Control cleans up after itself and does not leave dangling throttles
Because Cruise Control does not keep any state it's impossible to tell whether an existing throttle is present because a cluster administrator set the quota separate from Cruise Control, or if Cruise Control was restarted/failed/killed while rebalancing. I personally feel it's important that Cruise Control cleans up after itself and does not leave dangling throttles. I am open to feedback on this and can change my mind.

Overall it does feel like we're aligned and that we can probably sort out these questions in the PR! Thanks again for your feedback! We may start it this week, but will definitely start it next week!

**Comment by efeg** [comment]
That all sounds good -- I look forward to the PR!

**Comment by stanislavkozlovski** [comment]
@aaronlevin-stripe 

> My thoughts are that if a quota already exists we should leave it be (however I don't feel strongly). I'm assuming that any pre-existing quota is there because a kafka cluster administrator set it or because a previous Cruise Control-executed rebalance was restarted/killed/failed before completing. In both these cases I feel it's safest not to touch the existing quota.

Could you expand on the "because a previous Cruise Control-executed rebalance was restarted/killed/failed before completing"?

I was thinking - what do we do in the scenario where Cruise Control runs a rebalance, fails, the rebalance completes and then Cruise Control comes back up? We would be left with the throttles?

**Comment by aaronlevin-stripe** [comment]
@stanislavkozlovski it's complicated, but yes it's possible some throttles would be left. Cruise Control does not have any stateful storage so it's difficult to capture and restore the throttle state of the cluster.

**Comment by dxu-sfx** [comment]
@efeg @brettrann  Thanks for the post, it really gives me a choice.
I do have a question is, If I just want the overall cluster throttle, the only setup below is enough right? I do not necessarily need to specify replica or do it while some partition migration. 

kafka-configs.sh --zookeeper zoo1:2181/kafka --entity-type brokers --entity-name $brokerid --alter --add-config follower.replication.throttled.rate=30000000
kafka-configs.sh --zookeeper zoo1:2181/kafka --entity-type brokers --entity-name $brokerid --alter --add-config leader.replication.throttled.rate=30000000
