### ISSUE TITLE
There is a vulnerability in Apache ZooKeeper 3.5.7 ,upgrade recommended

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [linkedin/cruise-control#1546]
https://github.com/linkedin/cruise-control/blob/4ab12e12cca3cd983f8be9954882a3cf5fb2d0fc/gradle.properties#L5

CVE-2021-21409

Recommended upgrade version：
3.6.3

**Comment by efeg** [comment]
This issue has already been addressed in major versions (see https://github.com/linkedin/cruise-control/pull/1541):
* `2.0.165`
* `2.4.58`
* `2.5.50`

Note that we can avoid this CVE by explicitly specifying the version of Netty dependencies instead of relying on the version set by ZooKeeper.
Please let us know if there are any followup issues.
