### ISSUE TITLE
Multiple OS vulnerabilities found in Cruise Control version 2.5.46 , 2.5.50

### ISSUE THREAD

**Issue by KunalAdu** [linkedin/cruise-control#1556]
In Addition to previous ticket which got closed -https://github.com/linkedin/cruise-control/issues/1539 

Even after Updating to 2.5.50 I can see below vulnerabilities :
CVE-2019-18276
CVE-2019-12904
CVE-2016-2781
CVE-2020-9794
CVE-2020-9849
CVE-2020-9991
CVE-2021-20231
CVE-2021-20232
CVE-2018-20839
CVE-2013-4235
CVE-2019-20838
CVE-2019-13050
CVE-2019-25013
CVE-2020-27618
CVE-2020-29562
CVE-2020-6096
CVE-2021-27645
PRISMA-2021-0055
CVE-2021-2161
CVE-2021-2163

Is this safer version to upgrade ? 
Or please help us safer latest version

**Comment by efeg** [comment]
Hi @KunalAdu I read a few CVEs -- e.g. https://nvd.nist.gov/vuln/detail/CVE-2018-20839, https://nvd.nist.gov/vuln/detail/CVE-2020-9991, https://nvd.nist.gov/vuln/detail/CVE-2020-6096

It is not clear why such vulnerabilities are relevant to Cruise Control -- does the scanning tool provide a report on why it is raising these issues?
I suspect some of them (e.g. `PRISMA-2021-0055`) might be relevant to `commons-codec:commons-codec:1.11`, which is a transitive dependency fetched through the latest version of `httpclient` -- i.e. `org.apache.httpcomponents:httpclient:4.5.13`. I will explicitly specify the version of `commons-codec` dependencies instead of relying on the version pulled by `httpclient`.

> Is this safer version to upgrade ?
> Or please help us safer latest version

You may check the latest version in https://github.com/linkedin/cruise-control/releases
