### ISSUE TITLE
Suppress warning logs(Skip generating) in CC

### ISSUE THREAD

**Issue by lenin-joseph** [linkedin/cruise-control#2162]
Hi, 

Whenever we restart the Kafka pods, we see the below warning in the CC logs. The warning message seems misleading that "metrics are missing". Can this be suppressed? Does cruise control have any heartbeat mechanism to check the health of the Kafka broker before trying to get the metrics from that broker? 

{"version": "1.2.0", "timestamp": "2024-05-29T13:14:36.252+00:00", "severity": "warning", "service_id": "kafka-cluster", "message": "Skip generating metric sample for broker 0 because all broker metrics are missing.", "metadata": {"container_name": "cruise-control", "pod_name": "cluster-a-cruise-control-6979466c66-2ltnk"}, "extra_data": {"file": "SamplingUtils.java", "line": "295", "cluster_name": "cluster-a"}}

strimzi:  0.36.1
Kafka- 3.5.1
cruise-control-metrics-reporter-2.5.123.jar

Regards, 
Lenin

**Comment by mhratson** [comment]
> Does cruise control have any heartbeat mechanism to check the health of the Kafka broker before trying to get the metrics from that broker?

CC doesn't "get" metrics from the broker. Metrics is  produced by the `cruise-control-metrics-reporter` into `__CruiseControlMetrics` topic and later consumed by CC. 

More here: [WARN Skip generating metric sample for broker because all broker metrics are missing](https://github.com/linkedin/cruise-control/blob/main/docs/wiki/Troubleshooting.md#warn-skip-generating-metric-sample-for-broker-because-all-broker-metrics-are-missing)

**Comment by mhratson** [comment]
As for suppressing metrics you can either increase log level to skip `WARNING`s  or filter out those particular messages in your logging pipeline. 
There seem to be no way to suppress those warnings specifically at the moment.
