### ISSUE TITLE
Questions Regarding PreferredLeaderElectionGoal

### ISSUE THREAD

**Issue by wetcod** [linkedin/cruise-control#2185]
Hello, I am currently considering introducing CC within my team. 
However, I have a question regarding the PreferredLeaderElectionGoal.

1. Why is the `/rebalance` with PreferredLeaderElectionGoal continuously called every 5 minutes?
<img width="1099" alt="image" src="https://github.com/user-attachments/assets/9a3ae70d-d934-44d8-8dbf-71656bd6d9f2">

2. What is the difference between `auto.leader.rebalance.enable` and the `PreferredLeaderElectionGoal`? I believe that Kafka itself performs preferred leader rebalancing through `auto.leader.rebalance.enable`, but I am curious why CC handles it separately.

Thank you.

**Comment by dberardo-com** [comment]
i am new to cruise control and dont know if this is the right place to ask for this, but is the PreferredLeaderElectionGoal also usable for the use case i have?

one my kafka brokers is slower than the others (hardware differences), and i would like to keep it in the cluster only for high availability purposes. to achieve this i would like this broker to never become a partition leader, so i might have to rebuild replicas so that the order of the replica changes and the specific broker is always the last in the preferred leader list.

can cruise control be used for that ?

**Comment by mhratson** [comment]
> Why is the /rebalance with PreferredLeaderElectionGoal continuously called every 5 minutes?

Is this cruise-control UI? Can you check the CC logs and see the source?

> What is the difference between auto.leader.rebalance.enable and the PreferredLeaderElectionGoal?

They serve similar purpose. But if you're using CC then relying on kafka to balance cluster may interfere with CC, thus the separate goal i think.
