### ISSUE TITLE
Cruise-Control's behaviour on unintentional restart while its balancing

### ISSUE THREAD

**Issue by jmarkan** [linkedin/cruise-control#233]
Hello @efeg ,
We're very close to implementing cruise control in our environment and are running last bit of test case. I just have a quick question regarding expected Cruise Control behavior when it is doing a rebalance and gets restarted by mistake by anyone. Is it expected to continue the rebalance when its back? Would it cause any issues with the data stability on kafka brokers?

**Comment by efeg** [comment]
Hi @jmarkan ,
That is great to hear!
As of now, Cruise Control (CC) does not continue an interrupted `rebalance`, `add_broker`, or a `remove_broker` execution after it is bounced.
* CC performs task executions, e.g. replica movements, in batches. The particular batch of execution that has already been started by CC will continue in the Kafka cluster until completion, but the next planned batch of execution will not be started after the CC instance comes back up. 
* When the new instance of CC is up again, its `ExecutorState` will show `NO_TASK_IN_PROGRESS`. So, it won't show the progress of any potentially ongoing execution remaining from the previous execution. However, if you attempt to start a `rebalance`, `add_broker`, or a `remove_broker` operation while there are ongoing executions in the cluster, CC will detect that, and will not start a new execution until the cluster completes the ongoing execution. Hence, it will be safe in terms of data stability -- e.g. no extra replication or data loss.
* If `self_healing` is off, you may need to send the interrupted `rebalance`, `add_broker`, or `remove_broker` request again to complete an interrupted execution. Otherwise, if the goal violation or broker failure detector identifies an issue, it will attempt to fix it by taking the necessary action.

**Comment by jmarkan** [comment]
Awesome ! Thanks for your response @efeg , much appreciated. 

Sidebar - It will be great if CC could have a feature to discover the broker IDs (maybe via ZK endpoint provided in the config) and self-populate the capacity.json file. As for the capacities for each broker, that could be manually added by the user. WDYT?

**Comment by jmarkan** [comment]
Thanks @efeg , so if I understood it correctly if I put something like`broker.capacity.config.resolver.class=BrokerCapacityConfigResolver`  in cruise control config file, if will be able to put the broker ids in capacity.json file on the basis of kafka endpoint in the same config? or, is it something that needs to be implemented on the broker side?

**Comment by efeg** [comment]
Hey @jmarkan , sorry for the late response.

To achieve self-populating the `capacity.json` file:
1. You need to write your own class (e.g. `MyOwnCapacityConfigResolver`), which implements `BrokerCapacityConfigResolver` interface.
2. Then in cruise control config file, set the `broker.capacity.config.resolver.class=MyOwnCapacityConfigResolver`.

The default `BrokerCapacityConfigFileResolver` which also implements the `BrokerCapacityConfigResolver` interface does not support  auto-populating the `capacity.json` file.

**Comment by imans777** [comment]
It would have been great that this implementation (auto fetch new brokers/logdirs from kafka/zk api on a routine) would have existed by default on original cruise control. It's what many need.
