### ISSUE TITLE
Automatically reassign partitions to recovered brokers?

### ISSUE THREAD

**Issue by jeremydonahue** [linkedin/cruise-control#266]
Hi, 

I'm wondering if it's possible to automatically reassign partitions to recovered brokers? Here's what I'm seeing:

1. _Broker 1_ failure detected.
2. Replicas from _Broker 1_ are reassigned to existing brokers.
3. _Broker 1_ recovers and returns to the cluster.
4. _Broker 1_ is not assigned partitions until `add_broker` or `rebalance` is called.

Is it required/expected to have to call `add_broker` or `rebalance` for recovered brokers?

Thanks,
Jeremy

**Comment by chowell5** [comment]
I would appreciate clarification on this too.

**Comment by efeg** [comment]
Yes, currently it is required to call `add_broker` or `rebalance` for self-healing recovered brokers with no replicas.
Also due to the following configs, the self-healing would have a cooling period even when there are replicas assigned to such brokers (e.g. due to creation of new topics).

```
# True if recently removed brokers are excluded from optimizations during broker failure self healing, false otherwise
broker.failure.exclude.recently.removed.brokers=true

# True if recently removed brokers are excluded from optimizations during goal violation self healing, false otherwise
goal.violation.exclude.recently.removed.brokers=true

# The maximum time in milliseconds to retain the demotion history of brokers.
demotion.history.retention.time.ms=1209600000

# The maximum time in milliseconds to retain the removal history of brokers.
removal.history.retention.time.ms=1209600000
```

That being said, I think it is better to make the behavior regarding "not assigning new replicas to brokers with no replicas" configurable.

Thanks for reporting this! I know that this issue was discussed on our [Gitter channel](https://gitter.im/kafka-cruise-control/Lobby) -- but sorry for the late reply here!

**Comment by efeg** [comment]
To achieve this automatically (i.e. via self-healing) in the current version, users can either set `broker.failure.exclude.recently.removed.brokers` to `false` (default is `true`), or decrease the value of `removal.history.retention.time.ms` (default: `336hours` -- i.e. `2 weeks`).
