### ISSUE TITLE
Custom Sampler ( & Reporter)

### ISSUE THREAD

**Issue by krallistic** [linkedin/cruise-control#47]
If i understand correctly the default way is to use the CruiseControlMetricsReporter but it should be possible to use a different one.
For Example, if already have metrics in prometheus/graphite, i would need to write a different metric sampler for cruise-control...?
- What metrics are needed? 
- How would one write a different sampler?
- Is there documentation to do this?

**Comment by becketqin** [comment]
@krallistic Yes, you are right. `com.linkedin.kafka.cruisecontrol.monitor.sampling.MetricSampler` class is the interface. You can implement that. The metrics needed are `com.linkedin.kafka.cruisecontrol.monitor.sampling.PartitionMetricSample` and `com.linkedin.kafka.cruisecontrol.monitor.sampling.BrokerMetricSample`.

We don't have a wiki documentation for MetricSampler yet. But if you look at the interface it should be easy to understand.

I am also curious about the reason you don't want to use the default metrics reporter. At LinkedIn we are actually switching from the in house metric system to the default metrics reporter for better stability and lower latency. Is there any reason that you want to use graphite instead of the cruise control metrics reporter?

**Comment by krallistic** [comment]
Thank you, i will take a look at this (Is there a better place for questions? I couldnt find a Mailinglist, IRC...)

It feels unnecessary if a existing monitoring system is already used to introduce a second side channel for one tool . Also naturally i am hesitant to redeploying brokers with new jars.
But i will give the cruise-control reporter and try.

**Comment by becketqin** [comment]
You can join this gitter room to ask questions.
https://gitter.im/kafka-cruise-control/Lobby

**Comment by becketqin** [comment]
We initially thought that we would like to reuse the existing metric systems as well. But it turns out that introducing another external dependency just makes the system less stable.

**Comment by becketqin** [comment]
Closing this issue. We can talk in the gitter room.
