### ISSUE TITLE
isProposalReady is false

### ISSUE THREAD

**Issue by awartika** [linkedin/cruise-control#470]
cruise-control state shows all goals as ready but isProposalReady is still false. 

MonitorState: {state: RUNNING(20.000% trained), NumValidWindows: (1/1) (100.000%), NumValidPartitions: 506/506 (100.000%), flawedPartitions: 0}
ExecutorState: {state: NO_TASK_IN_PROGRESS}
AnalyzerState: {isProposalReady: false, ReadyGoals: [NetworkInboundUsageDistributionGoal, CpuUsageDistributionGoal, PotentialNwOutGoal, NetworkInboundCapacityGoal, LeaderBytesInDistributionGoal, DiskCapacityGoal, ReplicaDistributionGoal, RackAwareGoal, TopicReplicaDistributionGoal, NetworkOutboundCapacityGoal, CpuCapacityGoal, DiskUsageDistributionGoal, NetworkOutboundUsageDistributionGoal, ReplicaCapacityGoal]}

Monitored Windows [Window End_Time=Data_Completeness]:
{1546557600000=100.000%}

Goal Readiness:
                                     RackAwareGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.000, includedAllTopics=true), Ready
                               ReplicaCapacityGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.000, includedAllTopics=true), Ready
                                  DiskCapacityGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=true), Ready
                        NetworkInboundCapacityGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=true), Ready
                       NetworkOutboundCapacityGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=true), Ready
                                   CpuCapacityGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=true), Ready
                           ReplicaDistributionGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.000, includedAllTopics=true), Ready
                                PotentialNwOutGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=false), Ready
                         DiskUsageDistributionGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=true), Ready
               NetworkInboundUsageDistributionGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=false), Ready
              NetworkOutboundUsageDistributionGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=false), Ready
                          CpuUsageDistributionGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=false), Ready
                      TopicReplicaDistributionGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.000, includedAllTopics=true), Ready
                     LeaderBytesInDistributionGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=false), Ready

**Comment by kidkun** [comment]
what is the config value for `num.proposal.precompute.threads`.
looks like there is no proposal precomputing thread running in the background.

**Comment by awartika** [comment]
num.proposal.precompute.threads=1

**Comment by awartika** [comment]
All the config values are default values.

**Comment by efeg** [comment]
@awartika 
**Background:** `isProposalReady` indicates whether the cached proposals for rebalance requests with default goals are valid or not. These proposals are calculated either (1) via proposal precomputing thread in the background with some frequency configured by `proposal.expiration.ms`  (i.e. the default is once in every `15 minutes`), or (2) via a recent rebalance request with default goals (i.e. no goals provided in the request).

However due to the changes in the underlying cluster model, the cached proposals become stale. Recent patches (e.g. https://github.com/linkedin/cruise-control/issues/491) have helped increasing the time the cached proposal remains fresh. However, naturally, cache is expected to be stale at some point and then `isProposalReady` will be `false`. In such cases, the cache will be repopulated with a fresh proposal -- so it should have no impact on the user -- i.e. this field is just for information purposes you can ignore it.
