### ISSUE TITLE
Some properties not in KafkaCruiseControlConfig

### ISSUE THREAD

**Issue by zandegran** [linkedin/cruise-control#592]
```
metric.reporter.topic.pattern
partition.metric.sample.store.topic
broker.metric.sample.store.topic
sample.store.topic.replication.factor
num.sample.loading.threads
capacity.config.file
default.goals
hard.goals
min.monitored.partition.percentage
metric.anomaly.percentile.upper.threshold
metric.anomaly.percentile.lower.threshold
anomaly.detection.goals
metric.anomaly.analyzer.metrics
cluster.configs.file
self.healing.enabled
```

These properties are not defined in **KafkaCruiseControlConfig** in Migrate to 2.0 branch

**Comment by kidkun** [comment]
@zandegran The reason is that except these 3 config(which is defined in `KafkaCruiseControlConfig`)

> default.goals
hard.goals
min.monitored.partition.percentage

the other configs belong to pluggable component. For example, `metric.reporter.topic.pattern` belongs to `CruiseControlMetricsReporterSampler` which is just one implementation of the interface [MetricSampler](https://github.com/linkedin/cruise-control/blob/master/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/MetricSampler.java). With that being said, user of CC have freedom to implement this interface in their own way and this config become unneeded. That's why we do not put the config in `KafkaCruiseControlConfig`(which only contains core configs).

**Comment by zandegran** [comment]
Understood. Thanks for your reply.
