### ISSUE TITLE
Is it possible to move data from one broker to another?

### ISSUE THREAD

**Issue by BDeus** [linkedin/cruise-control#593]
I can't see an explicit config to remove a broker on specific one ?
Is it possible to add a parameter "destination_broker_id" on remove_broker api?

**Comment by kidkun** [comment]
IIUC, you want to do things like move all replica from broker A to broker B. 
If so, currently we do not support this kind of operation. In the past we have considered this feature, but we feel this contradicts with our design philosophy of `Cruise Control instead of human decides what is the best for the cluster`. And we have the long-term vision of Cruise Control to run with minimal human intervention, so these kinda management operation seem too ad-hoc.

**Comment by BDeus** [comment]
I understand this consideration. But what your recommandation to fully upgrade a kafka cluster? I was thinking to move data broker by broker to a new update node. But with Cruise Control automation i would have thought to let it do it with REST call.

**Comment by efeg** [comment]
@BDeus Fully upgrading a Kafka cluster is easy with Cruise Control -- you may follow the following steps:
-- Assume you have `N` old and `M` new brokers, and you would like to move the data from `N -> M`.
1. First attach the `M` new brokers to your cluster to have `M + N` brokers. At this point all data is on `N` brokers -- i.e. no partitions on any of the `M` brokers.
2. Then run `remove_broker?brokerid=<ids-of-N-brokers>`.
3. Sit back, and wait until the replica movement finishes while also providing full rebalance. To control the time this process takes, you may dynamically increase the concurrent replica movements using `admin` endpoint.

Please let us know if you encounter any issues.

**Comment by BDeus** [comment]
@efeg Thanks, that's what i have done.
First i was thinking to do it broker by broker but it was much easier to do this way.
The only thing that remaining is the throttle rate in the API  ;) (https://github.com/linkedin/cruise-control/issues/150)
