### ISSUE TITLE
Partition reassignment will stall indefinitely if a destination broker is unavailable

### ISSUE THREAD

**Issue by pmbuko** [linkedin/cruise-control#664]
If a broker failure occurs while a partition reassignment is underway, and the partition reassignment plan includes the failed broker as a destination for one or more topic partitions, the execution will stall indefinitely, requiring manual intervention to resolve.

Cruise control should be able to detect this situation, delete the problematic reassignment plan, and generate an updated one.

**Comment by kidkun** [comment]
Thanks for reporting this. 

There are actually two issues in CC's current handling logic for this scenario.
1) hang in execution. Unless the failed destination broker is for a new replica for this partition, CC will hang.
An example is for a cluster of broker [1,2,3,4]  and broker 1 is down, CC generate a proposal [1,2] -> [2,3].
 If broker 3 is down during this proposal's execution, this proposal will be aborted and CC will finish(but this task will still persist in znode `admin/partition_reassignment` until manual znode deletion or broker 3 is recovered)
if broker 2 is down during execution, CC will not mark this task as done because it is a not a new replica for the partition and the execution will hang for undefined time

2) if it takes CC a long time to self-heal an broker failure( could be because of hang described above) and another broker dies during the self-healing, the self-healing for this new dead broker will never be triggered, even after the first  self-healing has finished

So we need to fix the above two issue
for 1), CC should never hang, if it detects any destination broker for any proposal is dead, it should abort the proposal immediately
for 2), CC should somehow remember the any broker failure during execution and come back to check if the broker is still dead after finishing current execution

With this fix, there is still a caveat worthy special attention. For issue 1), even if the hanged proposal is marked aborted in CC, CC will not try to delete the znode(otherwise this partition will be in a indeterministic state), so this still needs human invention, CC can send some alert for this case.

**Comment by pmbuko** [comment]
For the caveat, if you feel it is outside CC's scope, I don't have an issue handling the removal separately with my own automation. I don't use CC for alerting, so if could detect a state needing manual intervention via an API call, that would be ideal.

**Comment by kidkun** [comment]
Take a more closer look at our current handling logic and it is capable of dealing with above-mentioned issues.
1.  for each of the proposals,  if it is a leadership change proposal and new leader's broker is dead or is a replica movement proposal and any of replica in new replica list's broker is dead, the proposal is [marked as dead](https://github.com/linkedin/cruise-control/blob/8b4b8ad3dbd00378420193a9da160ff3797ab703/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java#L847), and [current execution is stopped](https://github.com/linkedin/cruise-control/blob/8b4b8ad3dbd00378420193a9da160ff3797ab703/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java#L760). 
So in above example, if broker 2 is dead, CC is able to abort the proposal and whole execution and go back to idle immediately( and next detected anomaly will contains the newly dead broker and if self-heal is enabled, the new fix will fix the newly dead broker)

2. if a broker dead happens in the middle of an execution, anomaly detector will [keep scheduling another check  with some delay](https://github.com/linkedin/cruise-control/blob/8b4b8ad3dbd00378420193a9da160ff3797ab703/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/AnomalyDetector.java#L263), so that after current execution is done, anomaly detector will come back to check and if broker is still dead, a self-healing operation will be triggered for this dead broker, no anomaly will be ignored.

For the caveat mentioned above, it is still valid.  And the reason we do not want to delete `partition_reassignment` znode though CC is because currently Kafka does not handle `partition_reassignment` updating(see [KAFKA-6304](https://issues.apache.org/jira/browse/KAFKA-6304), if we delete the znode, Kafka controller is unable to rollback and the subject topic partition will have a replica list of a mix of new and old replicas.  So in scenario we feel it is better to have human intervention( to delete znode, bounce controller and write a new proposal to `partition_reassignment` znode to make sure the topic partition is parked in a deterministic state).
