### ISSUE TITLE
Possibility to remove a broker without valid_windows

### ISSUE THREAD

**Issue by BDeus** [linkedin/cruise-control#695]
Hi,
i tried to remove a failed broker with remove_broker API,
but i don't have any valid windows anymore on cruise control since this broker is down.
Is it possible to force a call to remove_broker with no valid_windows ?
Thanks

CC Error:
`error processing POST request '/remove_broker' due to: 'com.linkedin.kafka.cruisecontrol.exception.KafkaCruiseControlException: com.linkedin.cruisecontrol.exception.NotEnoughValidWindowsException: There are only 0 valid windows when aggregating in range [-1, 1557395614349] for aggregation options (minValidEntityRatio=1.00, minValidEntityGroupRatio=0.00, minValidWindows=1, numEntitiesToInclude=222, granularity=ENTITY_GROUP)'.`

**Comment by efeg** [comment]
@BDeus Thanks for bringing up this issue!

While this feature is currently not supported by Cruise Control, it should indeed be possible to run `rebalance`, `add_broker`, `remove_broker`, and `fix_offline_replicas` operations using a selected set of goals (e.g. RackAwareness, ReplicaDistribution, ReplicaCapacity) without the need for collecting / using `load` information -- i.e. without a valid window, simply based on replica distribution information over the brokers.

This feature not only helps increasing the availability of CC, but also makes the process of proposal generation faster -- because cluster model generation without the load information should be quick. @BDeus would you be interested in contributing on this?

**Comment by efeg** [comment]
https://github.com/linkedin/cruise-control/pull/962 has added support to run executions w/o windows using selected goals, including RackAwareness, ReplicaDistribution, ReplicaCapacity, TopicReplicaDistribution, and PLE.
