### ISSUE TITLE
When Cruise Control loses ZK session during reassign partition, it should not quit the reassign attempt after it establishes another ZK session

### ISSUE THREAD

**Issue by zornhsu** [linkedin/cruise-control#785]
E.g., Cruise Control GC takes X seconds which is more than the zk session timeout. 
If a reassign partition was in progress, CC would not continue the same reassign attempt after it establishes another ZK session.

**Comment by efeg** [comment]
`migrate_to_kafka_2_4`, which is the branch for Kafka 2.4 deployments, has adopted AdminClient-based replica reassignment API rather than using ZK (see https://github.com/linkedin/cruise-control/pull/1196). Moreover, both `master` and `migrate_to_kafka_2_4` have migrated to adopt `JDK 11`, which provides significantly lower GC pause times (see http://mail.openjdk.java.net/pipermail/hotspot-gc-use/2018-June/002759.html)
