### ISSUE TITLE
Centralization schedule question

### ISSUE THREAD

**Issue by q6413260** [linkedin/cruise-control#81]
Hello，I have a question：
i think it is impossible for u to haven only one server to deploy  cruise-control。
if i have serval servers to deploy cruise-control，
all of the servers will monitor，analyzer，detector，finally
execute the preposals。if so，the preposals will be executed
more than once？
i want to know how do you handle this in your product environment

**Comment by becketqin** [comment]
@q6413260 You are right that we don't run two CC for a Kafka cluster. Typically it is fine because CC is not as critical as Kafka itself. If it dies, as long as we can detect and restart it quickly it is OK. We do have alerts if CC dies and we will restart it.

BTW, it is probably better to ask such questions in our gitter room than creating an issue. https://gitter.im/kafka-cruise-control/Lobby

**Comment by q6413260** [comment]
@becketqin ok.I will join your gitter room.And one more question. You say you run CC for a kafka cluster. In fact, we want wo design automate the dynamic workload rebalance and self-healing of redis clusters like your CC.In our product environment，we have 700 redis clusters and nearly 10000 redis server nodes。
 I want to know how many brokers in your one kafka cluster,
