### ISSUE TITLE
cruise-control adds broker to "recentlyRemovedBrokers" even though broker removal couldn't start

### ISSUE THREAD

**Issue by mgrubent** [linkedin/cruise-control#833]
```
[mgrubent@box ~]$ cccli -a place:port remove-broker host27636.linkedin.com 
'errorMessage':
("Error processing POST request '/remove_broker' due to: "
 "'java.lang.IllegalStateException: Cannot execute new proposals while there "
 "is an ongoing execution.'.")
```
And yet
```
[mgrubent@box ~]$ cccli -a place:port state 
'ExecutorState':
{'recentlyRemovedBrokers': [27636], 'state': 'NO_TASK_IN_PROGRESS'}
```

**Comment by efeg** [comment]
The latest version of CC checks for ongoing executions before adding broker(s) to be removed to the `recentlyRemovedBrokers`. Hence, this scenario does not add brokers to "recentlyRemovedBrokers" when a broker removal couldn't start.

That being said, if a broker removal execution is interrupted either via user (i.e. `stop_ongoing_execution`) or due to a broker failure, such being-removed brokers will remain as part of `recentlyRemovedBrokers`. This helps having pluggable goals (e.g. a custom `MaintenanceAwareGoal`) that removes such brokers once the execution can start again.
